### ISSUE TITLE
crash with softhdvaapi/cuvid

### ISSUE THREAD

**Issue by 9000h** [Zabrimus/vdr-plugin-hbbtv#2]
the plugin still suffers from the same issue skinnopacity and tvguide had
width = 1921, height = 1081, viewPortWidth = 1921, viewPortHeight = 1081

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `vdr -l3 -w 60 --chartab=ISO-8859-1 -Phbbtv -Ptvguide -Pfemon -Pextrecmenu -Pepg'.
--Type <RET> for more, q to quit, c to continue without paging--
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fbc7a54b700 (LWP 8449))]
(gdb) br
Breakpoint 1 at 0x7fbd0696eed7: file ../sysdeps/unix/sysv/linux/raise.c, line 50.
(gdb) bt
#0  0x00007fbd0696eed7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fbd069505fe in __GI_abort () at abort.c:100
#2  0x00007fbd0544fce0 in  () at /lib/libGraphicsMagick-Q16.so.3
#3  0x00007fbd06f8ff40 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007fbca5e6f9ea in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fbca5e70622 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#6  0x00007fbca59a096e in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#7  0x00007fbca5a9a18f in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#8  0x00007fbca5a9a5a2 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#9  0x00007fbd012de057 in cOglCmdCopyBufferToOutputFb::Execute() (this=0x7fbc1c001d80) at openglosd.h:233
#10 0x00007fbd012e272b in cOglThread::Action() (this=0x55cabe2f15f0) at openglosd.cpp:1639
#11 0x00007fbd012e272b in cOglThread::Action() (this=0x55cabe2f15f0) at openglosd.cpp:1587
#12 0x000055cababe3591 in cThread::StartThread(cThread*) (Thread=0x55cabe2f15f0) at thread.c:293
#13 0x00007fbd06f85182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#14 0x00007fbd06a48b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) up
#1  0x00007fbd069505fe in __GI_abort () at abort.c:100
100	abort.c: No such file or directory.
(gdb) up
#2  0x00007fbd0544fce0 in ?? () from /lib/libGraphicsMagick-Q16.so.3
(gdb) up
#3  <signal handler called>
(gdb) up
#4  0x00007fbca5e6f9ea in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) up
#5  0x00007fbca5e70622 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) up
#6  0x00007fbca59a096e in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) up
#7  0x00007fbca5a9a18f in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) up
#8  0x00007fbca5a9a5a2 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) up
#9  0x00007fbd012de057 in cOglCmdCopyBufferToOutputFb::Execute (this=0x7fbc1c001d80) at openglosd.h:233
233	        return height;
(gdb) print *this
$1 = {<cOglCmd> = {_vptr.cOglCmd = 0x7fbd012f6410 <vtable for cOglCmdCopyBufferToOutputFb+16>, fb = 0x55cabd6eef50}, oFb = 0x55cabd6f2450, x = 0, y = 0}
(gdb) print fb
$2 = (cOglFb *) 0x55cabd6eef50
(gdb) print *fb
$3 = {_vptr.cOglFb = 0x7fbd012f62c0 <vtable for cOglFb+16>, initiated = true, width = 1921, height = 1081, viewPortWidth = 1921, viewPortHeight = 1081, scrollable = false, fb = 56, 
  texture = 254}
(gdb) 
```

here is the fix for it
```
--- browser.c.orig	2020-03-12 20:35:05.340221936 +0100
+++ browser.c	2020-03-12 20:35:35.764503343 +0100
@@ -205,7 +205,7 @@
 
     osd = cOsdProvider::NewOsd(left, top);
 
-    tArea Area = { 0, 0, width, height, 32 };
+    tArea Area = { 0, 0, width - 1, height - 1, 32 };
     osd->SetAreas(&Area, 1);
 
     cRect rect(0, 0, width, height);
```

**Comment by Zabrimus** [comment]
committed the proposed change. 

VDR reports a value increased by 1 for for width and height of the tArea:
int Width(void) const { return x2 - x1 + 1; }
int Height(void) const { return y2 - y1 + 1; }

**Comment by 9000h** [comment]
yes, but nut sure why
